export const UiSizes = {
  ios: {
    statusBarHeight: 44,
    largeTitleBarHeight: 52,
    largeTitleFontSize: 34,
    navBarHeight: 44,
    navBarFontSize: 17,
    pageSidePadding: 16,
    tabBarHeight: 49,
    tabBarIconHeight: 24,
    homeIndicatorHeight: 34,
    searchInputContainerHeight: 51,
    searchInputContainerPadding: 8,
    searchInputFontSize: 17,
  },
  android: {
    statusBarHeight: 0,
    largeTitleBarHeight: 50,
    largeTitleFontSize: 34,
    navBarHeight: 56,
    navBarFontSize: 20,
    pageSidePadding: 16,
    tabBarHeight: 56,
    tabBarIconHeight: 24,
    homeIndicatorHeight: 0,
    searchInputContainerHeight: 55,
    searchInputContainerPadding: 8,
    searchInputFontSize: 16,
  },
};
